[[main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[main.params]
icon = "home"
newtab = false

[[main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2
[main.params]
icon = "user"
newtab = false

[[main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 3
[main.params]
icon = "archives"
newtab = false

[[main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 4
[main.params]
icon = "search"
newtab = false

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/"
[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/"
[social.params]
icon = "brand-twitter"

